MODEL_DIR          = ./MODEL
APB_UNIT_1_DIR     = ${MODEL_DIR}/APB_EXE_UNIT_1
APB_UNIT_2_DIR     = ${MODEL_DIR}/APB_EXE_UNIT_2
APB_CONTROLLER_DIR = ${MODEL_DIR}/APB_CONTROLLER
APB_BUS_DIR        = ${MODEL_DIR}/APB_APB_BUS
BUILD_DIR          = ./WORK



clear:
	rm -r ${BUILD_DIR}/* || true
